"""Add phone number to user table

Revision ID: 505d00fd6ee0
Revises: 936dcc753d97
Create Date: 2024-09-02 20:02:06.838294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '505d00fd6ee0'
down_revision: Union[str, None] = '936dcc753d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authentication', sa.Column('phonenumber', sa.String(), nullable=True))
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_column('authentication', 'phonenumber')
    # ### end Alembic commands ###
