name: Build and deployment
on: [push, pull_request]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2 #this action is taken from github action that automatically pulls the repo
      - name: welcome pranav
        run: echo "hello pranav"
